//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKMES.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.145.12; Port=5432; User Id=pqm; Password=dbuser; Database=pqmdb; C" +
            "ommandTimeout=100; Timeout=100;")]
        public string PQMDB_CONNECTION {
            get {
                return ((string)(this["PQMDB_CONNECTION"]));
            }
            set {
                this["PQMDB_CONNECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.145.12; Port=5432; User Id=pqm; Password=dbuser; Database=mesdb; C" +
            "ommandTimeout=100; Timeout=100;")]
        public string MESDB_CONNECTION {
            get {
                return ((string)(this["MESDB_CONNECTION"]));
            }
            set {
                this["MESDB_CONNECTION"] = value;
            }
        }
    }
}
